//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuubiWebApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TuubiWebApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METROPOLIA.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password you entered isn&apos;t correct. Try entering it again..
        /// </summary>
        public static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use light version of Outlook Web App.
        /// </summary>
        public static string lightVersionCheckbox {
            get {
                return ResourceManager.GetString("lightVersionCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The light version of Outlook Web App includes fewer features. Use it if you&apos;re on a slow connection or using a computer with unusually strict browser security settings. We also support the full Outlook Web App experience on some browsers on Windows, Mac, and Linux computers. To check out all the supported browsers and operating systems, click here..
        /// </summary>
        public static string lightVersionCheckBoxAlert {
            get {
                return ResourceManager.GetString("lightVersionCheckBoxAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail web app.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string passwordTitle {
            get {
                return ResourceManager.GetString("passwordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private computer.
        /// </summary>
        public static string privateRadioButton {
            get {
                return ResourceManager.GetString("privateRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: By selecting this option, you confirm that this computer complies with your organization&apos;s security policy..
        /// </summary>
        public static string privateRadioButtonAlert {
            get {
                return ResourceManager.GetString("privateRadioButtonAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you&apos;re the only person who uses this computer. Your server will allow a longer period of inactivity before signing you out..
        /// </summary>
        public static string privateRadioButtonHelp {
            get {
                return ResourceManager.GetString("privateRadioButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a public or shared computer.
        /// </summary>
        public static string publicRadioButton {
            get {
                return ResourceManager.GetString("publicRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you use Outlook Web App on a public computer. Be sure to sign out when you&apos;ve finished and close all windows to end your session..
        /// </summary>
        public static string publicRadioButtonHelp {
            get {
                return ResourceManager.GetString("publicRadioButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide explanation.
        /// </summary>
        public static string securityHideExplanationTrigger {
            get {
                return ResourceManager.GetString("securityHideExplanationTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show explanation.
        /// </summary>
        public static string securityShowExplanationTrigger {
            get {
                return ResourceManager.GetString("securityShowExplanationTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string securityTitle {
            get {
                return ResourceManager.GetString("securityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string signInButton {
            get {
                return ResourceManager.GetString("signInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful!.
        /// </summary>
        public static string successMessage {
            get {
                return ResourceManager.GetString("successMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string usernameTitle {
            get {
                return ResourceManager.GetString("usernameTitle", resourceCulture);
            }
        }
    }
}
